import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatChipsModule } from '@angular/material/chips';

import {
  MatAutocompleteModule,
  MatButtonModule,
  MatToolbarModule,
  MatSidenavModule,
  MatCheckboxModule,
  MatIconModule,
  MatFormFieldModule,
  MatOptionModule,
  MatSelectModule,
  MatRadioModule,
  MatInputModule,
  MatCardModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatTabsModule,
  MatSnackBarModule,
  MatExpansionModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatGridListModule,
  MatProgressBarModule,
  MatPaginatorModule,
  MatDividerModule,
  MatTooltipModule,
  MatProgressSpinnerModule,
  MatListModule,
  MatStepperModule,
  MatTableModule,
  MatMenuModule,
  MatDatepicker,
  MatDialogModule,
  ErrorStateMatcher,
  ShowOnDirtyErrorStateMatcher,
  MatRippleModule,
  MatSortModule,

} from '@angular/material';

@NgModule({
  imports: [
    MatAutocompleteModule,
    MatButtonModule,
    MatToolbarModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatIconModule,
    MatFormFieldModule,
    MatOptionModule,
    MatSelectModule,
    MatRadioModule,
    MatInputModule,
    MatCardModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTabsModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatSliderModule,

    MatSlideToggleModule,
    MatGridListModule,
    MatProgressBarModule,
    MatPaginatorModule,
    MatDividerModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatStepperModule,
    MatChipsModule,
    MatTableModule,
    MatMenuModule,
    MatSortModule,
    MatRippleModule,
    MatDialogModule
  ],

  exports: [
    MatAutocompleteModule,
    MatButtonModule,
    MatToolbarModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatIconModule,
    MatFormFieldModule,
    MatOptionModule,
    MatSelectModule,
    MatRadioModule,
    MatInputModule,
    MatCardModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTabsModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatProgressBarModule,
    MatPaginatorModule,
    MatDividerModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatStepperModule,
    MatTableModule,
    MatMenuModule,
    MatSortModule,
    MatRippleModule,
    MatChipsModule,
    MatDialogModule
  ],

  providers: [
    { provide: ErrorStateMatcher, useClass: ShowOnDirtyErrorStateMatcher }
  ]
})
export class MaterialModule { }